name: Build Project (Linux)

on:
  push:
    branches:
      - master
      - servicing
  pull_request:
    branches:
      - master
      - servicing
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Solution Compilation
      run: dotnet build --configuration Debug "Kernel Simulator.sln"
    - name: Testing
      run: dotnet test "Kernel Simulator.sln"
    - uses: actions/upload-artifact@v3
      with:
        name: ks-build
        path: "public/Kernel Simulator/KSBuild/net6.0/"
    - uses: actions/upload-artifact@v3
      with:
        name: ks-build
        path: "public/Kernel Simulator/KSBuild/*.nupkg"

  notify:

    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ always() }}
    
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.G_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
        
