name: Build Project (Release)

on:
  push:
    branches: [ "main", "v0.1.0.x-saas", "v0.1.1.x-saas", "v0.1.2.x-saas" ]
  pull_request:
    branches: [ "main", "v0.1.0.x-saas", "v0.1.1.x-saas", "v0.1.2.x-saas" ]
    
jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Solution Compilation (Windows)
      if: matrix.runs-on == 'windows-latest'
      run: cd tools ; ./build.cmd Release -p:ContinuousIntegrationBuild=true ; cd ..
    - name: Solution Compilation (Unix)
      if: matrix.runs-on != 'windows-latest'
      run: make rel-ci
    - name: Testing
      run: dotnet test --no-build --configuration Release
    - uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: unit-test-log-${{ matrix.runs-on }}
        path: "private/Nitrocid.Tests/KSTest/net8.0/UnitTestDebug.log"
    - uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: unit-test-log-ms-${{ matrix.runs-on }}
        path: "private/Nitrocid.Tests/KSTest/net8.0/TestResults"

  wix-amd64:
    strategy:
      fail-fast: false
    runs-on: "windows-latest"

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Solution Compilation
      run: cd tools ; ./build.cmd ; cd ..
    - name: Installer Solution Compilation
      run: dotnet build -p:Configuration=Release -p:Platform=x64 public/Nitrocid.Installers/Nitrocid.Installer.sln
    - uses: actions/upload-artifact@v4
      with:
        name: installer-x64-msi
        path: "public/Nitrocid.Installers/Nitrocid.InstallerBundle/bin/x64/Release"

  wix-arm64:
    strategy:
      fail-fast: false
    runs-on: "windows-latest"

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Solution Compilation
      run: cd tools ; ./build.cmd ; cd ..
    - name: Installer Solution Compilation
      run: dotnet build -p:Configuration=Release -p:Platform=ARM64 public/Nitrocid.Installers/Nitrocid.Installer.sln
    - uses: actions/upload-artifact@v4
      with:
        name: installer-arm64-msi
        path: "public/Nitrocid.Installers/Nitrocid.InstallerBundle/bin/ARM64/Release"
        
