name: Build Project (Debug)

on:
  push:
    branches: [ "main", "v0.1.0.x-saas" ]
  pull_request:
    branches: [ "main", "v0.1.0.x-saas" ]
    
jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Solution Compilation
      run: dotnet build -maxCpuCount:1 --configuration Debug
    - name: Testing
      run: dotnet test --no-build --configuration Debug
    - uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: unit-test-log-${{ matrix.runs-on }}
        path: "private/Nitrocid.Tests/KSTest/net8.0/UnitTestDebug.log"
    - uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: unit-test-log-ms-${{ matrix.runs-on }}
        path: "private/Nitrocid.Tests/KSTest/net8.0/TestResults"
        
