name: Build Project (macOS, Release)

on:
  push:
    branches:
      - main
      - servicing
  pull_request:
    branches:
      - main
      - servicing
    
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Solution Compilation
      run: dotnet build -maxCpuCount:1 --configuration Release
    - name: Testing
      run: dotnet test --no-build --configuration Release
    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: unit-test-log
        path: "private/Nitrocid.Tests/KSTest/net8.0/UnitTestDebug.log"

  notify:

    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ always() }}
    
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.G_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
        
