name: Build Project (Release)

on:
  push:
    branches: [ "main", "v0.0.24.x-saas", "v0.1.0.x-saas", "v0.0.24.x-saas" ]
  pull_request:
    branches: [ "main", "v0.0.24.x-saas", "v0.1.0.x-saas", "v0.0.24.x-saas" ]
    
jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Solution Compilation (Windows)
      if: matrix.runs-on == 'windows-latest'
      run: cd tools ; ./build.cmd ; cd ..
    - name: Solution Compilation (Unix)
      if: matrix.runs-on != 'windows-latest'
      run: make
    - name: Testing
      run: dotnet test --no-build --configuration Release
        
