name: Build Project (for Launchpad PPA)

on:
  push:
    branches:
      - main
      - servicing
  pull_request:
    branches:
      - main
      - servicing


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install required packages
        run: |
          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt update
          sudo apt purge dotnet*
          sudo apt autoremove
          sudo apt install curl locales-all cli-common-dev libunwind8-dev libcurl4-openssl-dev dotnet-sdk-7.0 devscripts debhelper-compat dput
        
      - name: Initialize offline package
        run: |
          sudo ip netns add no-net
          chmod +x tools/initializeoffline.sh
          make debian-init-offline
        
      - name: Try to build
        run: |
          cd Kernel-Simulator
          sudo ip netns exec no-net make debian-all-offline
