name: Build Project (macOS)

on:
  push:
    branches:
      - main
      - servicing
  pull_request:
    branches:
      - main
      - servicing
    
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Solution Compilation
      run: dotnet build -maxCpuCount:1 --configuration Debug
    - name: Testing
      run: dotnet test --no-build --configuration Debug
    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: ks-build
        path: "public/Nitrocid/KSBuild/net8.0/"
    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: ks-build
        path: "public/Nitrocid/KSBuild/*.nupkg"
    - uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: unit-test-log
        path: "private/Nitrocid.Tests/KSTest/net8.0/UnitTestDebug.log"
        
