name: Chocolatey Gallery Push

on:
  release:
    types: [released]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: API Key Preparation
      run: choco apikey --key ${{ secrets.CHOCO_APIKEY }} --source https://push.chocolatey.org/
    - name: Application Pack
      run: |
        $path = "ChocolateyPack"
        $pathdotnet = "ChocolateyPack-DotNet"
        choco pack (Get-Item "$path\ks.nuspec").FullName
        choco pack (Get-Item "$pathdotnet\ks.nuspec").FullName
    - name: Package Publication
      run: |
        $FileName = Get-ChildItem -Path $pwd.Path -Name -Filter "KS*.nupkg"
        foreach($fn in $FileName) {
            choco push "$pwd\$fn"
        }
