name: Package Registry Push

on:
  release:
    types: [published]
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: NuGet Installation
      uses: nuget/setup-nuget@v1
      with: 
        nuget-version: "latest"
    - name: CURL Installation
      run: choco install curl
    - name: MSBuild Installation
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Dependency Restoration
      run: nuget restore "Kernel Simulator.sln"
    - name: Solution Compilation
      run: msbuild "Kernel Simulator.sln" /p:DefineConstants=NTFSCorruptionFix /p:Configuration=Release
    - name: Package Publication
      run: |
        $path = "Kernel Simulator\KSBuild"
        $FileName = Get-ChildItem -Path $path -Recurse -Name -Filter "*symbols*"
        curl -vX PUT -u "EoflaOE:${{ secrets.GITHUB_APIKEY }}" -F package="@$path\$FileName" https://nuget.pkg.github.com/EoflaOE/
