name: Publish release on tag
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: MSBuild Installation
      uses: microsoft/setup-msbuild@v1.0.2
    - uses: "nunit/docfx-action@v1.7.0"
      name: Generating documentation
      with:
        args: DocGen/docfx.json
    - name: Run build scripts
      shell: cmd
      run: |
        tools\build.cmd
        tools\build-dotnet.cmd
        tools\pack.cmd
        tools\pack-dotnet.cmd
        tools\docgen-pack.cmd
    - name: Make a release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          tools\*.rar
          tools\*.pdb
        draft: true
        name: "Version"
